jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:20.10.17-git  # Latest stable Docker image with Git pre-installed
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py3-pip
            pip install --upgrade setuptools
            apk add build-base python3-dev libffi-dev
            pip install docker-compose==1.29.2
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py