jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:20.10.17-git  # Latest stable Docker image with Git pre-installed
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17  # Matches the Docker version used in the image
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py3-pip
            pip install --upgrade setuptools
            pip install "Cython<3.0.0"
            pip install wheel  # Install wheel before docker-compose
            apk add build-base python3-dev libffi-dev
            pip install docker-compose==1.29.2 --no-build-isolation
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            # docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            # docker push $DOCKER_HUB_USER_ID/dockerapp:latest